- hosts: jumpbox
  gather_facts: false
  vars:
    deployment: dev
  tasks:
  - name: Destroy a frontend server instance
    os_server:
      cloud: ospcloud
      name: "{{ item }}"
      state: absent
    with_items:
    - app1
    - app2