---
  - name: install progress
    yum:
      name: postgresql-server
      state: latest

  - name: enable apache at boot
    service:
      name: postgresql
      enabled: yes
  - name: tell user to finish setting up postgres
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

  - name: initilize postgres
    command: "postgresql-setup initdb"
  - name: initilize postgres some more
    command: "chkconfig postgresql on"
  - name: start postgres
    service:
      name: postgresql.service
      state: started
  - name: adding port 5432/tcp & restarts firewalld
    firewalld:
      port: 5432/tcp
      permanent: true
      state: enabled
  - name: restart firewalld for dbtier
    service:
    name: firewalld
    state: restarted
